version: '3.9'

services:
  backend:
    image: lazyfoxx/flashmind-backend:latest  # замените на реальный username
    container_name: flashmind-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    
    
      # добавьте другие переменные окружения при необходимости
    # volumes:
    #   - ./data:/app/data  # если нужны persistent данные

  # Пример добавления других сервисов в будущем:
  # backend:
  #   image: otheruser/anki-clone-backend:latest
  #   restart: unless-stopped
  #   depends_on:
  #     - database

  # database:
  #   image: postgres:16
  #   restart: unless-stopped
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
