version: '3.9'

services:
  auth:
    image: lazyfoxx/flashmind-auth:${TAG:-latest}
    container_name: backend-auth
    restart: unless-stopped
    env_file:
      - .env.auth
    ports:
      - "8000:8000"
    depends_on:
      auth-postgres:
        condition: service_healthy
      auth-redis:
        condition: service_started
    secrets:
      - jwt_private_key
      - jwt_public_key
    networks:
      - auth-network
      - app-network
    command: sh -c "
      alembic upgrade head &&
      uvicorn src.main:app --host 0.0.0.0 --port 8000
      "
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"   # Порт RabbitMQ для обмена сообщениями
      - "15672:15672" # Веб-менеджер RabbitMQ для мониторинга
    networks:
      - app-network
  auth-postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env.auth
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # другой порт, чтобы не конфликтовать с локальной БД
    networks:
      - auth-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-redis:
    image: redis:7-alpine
    restart: unless-stopped
    env_file:
      - .env.auth
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server
      --appendonly yes
      --requirepass "${REDIS_PASSWORD}"
    volumes:
      - redis_data_auth:/data
    ports:
      - "6380:6379"
    networks:
      - auth-network
  frontend:
    image: lazyfoxx/flashmind-frontend:${TAG:-latest}
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  postgres_data_auth:
  redis_data_auth:

networks:
  auth-network:
    driver: bridge
  app-network:
    driver: bridge

secrets:
  jwt_private_key:
    file: ./keys/private_key.pem
  jwt_public_key:
    file: ./keys/public_key.pem
